# Site settings
title: Kyle Kneitinger
email: kyle@kneit.in
description: > # this means to ignore newlines until "baseurl:"
    The personal homepage of Kyle Kneitinger, a student, programmer, musician & 
baseurl: "/ger" # the subpath of your site, e.g. /blog/
url: "kneit.in" # the base hostname & protocol for your site
twitter_username: kneitinger
github_username:  kneitinger

# Build settings
markdown: kramdown
