# Site settings
title: kyle kneitinger
email: kyle@kneit.in
github: kneitinger
description: > # this means to ignore newlines until "baseurl:"
    The personal homepage of Kyle Kneitinger: musician, programmer & student
baseurl: "/ger" # the subpath of your site, e.g. /blog/
url: "kneit.in" # the base hostname & protocol for your site
twitter_username: kneitinger
github_username:  kneitinger

# Build settings
markdown: kramdown
